### ISSUE TITLE
Please add more in the ReadME

### ISSUE THREAD

**Issue by pr0PM** [brookmg/Sing#3]
Hi,
Please add more details in the readme file so that contributors can at least know what is thing about, no body will like to figure out about a project by reading it's source code.
Check this out: https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-readmes

**Comment by brookmg** [comment]
Yap, I have done that. Was kinda hoping for other people to start from there but it's done now. Check out the readme now.
